# Generated by Django 2.2.6 on 2019-10-29 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('is_in_public_domain', models.BooleanField(default=False)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('birtday', models.DateField(blank=True, null=True)),
                ('biogram', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=30)),
                ('cover_type', models.CharField(choices=[('soft', 'soft'), ('hard', 'hard')], default='soft', max_length=30)),
                ('pages', models.IntegerField(max_length=4)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover')),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('loan_data', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 29, 10, 25, 22, 137520, tzinfo=utc), null=True)),
                ('is_avaiable', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(to='books.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
